site_name: ARMxtend
site_url: http://cjferba.github.io/ARMxtend
site_author: Carlos Fernandez-Basso
site_description: A library consisting of useful tools for association rule mining.

repo_url: https://github.com/cjferba/ARMxtend
repo_name: GitHub
edit_uri: docs/user_guide/

#include_search: true # not necessary for this theme
docs_dir: sources

#theme:
#    name: null
#    custom_dir: 'custom_theme/'

markdown_extensions:
  - tables
  - fenced_code

copyright: Copyright &copy; 2016-2026 <a href="http://cjferba.github.com">Carlos Fernandez-Basso</a>

nav:
- Home: index.md
- Installation: installation.md
- Quick Start: quick-start.md
- Examples: examples.md
- User Guide:
  - USER_GUIDE_INDEX.md
  - Crisp association rules:
    - ARM.association_rules: user_guide/ARM/association_rules.md
    - FFIM (FP-Growth): user_guide/FFIM.md
  - Fuzzy association rules:
    - FIM.FARE: user_guide/FIM/FARE.md
  - Big Data (Spark) - crisp:
    - FIM.apriori (DApriori/DAprioriTID): user_guide/FIM/apriori.md
    - FIM.Eclat (DECLAT): user_guide/FIM/Eclat.md
    - FIM.BD_ARE: user_guide/FIM/BD_ARE.md
  - Big Data (Spark) - fuzzy:
    - FIM.BD_FARE (FuzzyDAprioriTID): user_guide/FIM/BD_FARE.md
    - FIM.Eclat (FuzzyDECLAT): user_guide/FIM/Eclat.md
  - Streaming (Spark):
    - SFIM / SARE (FIMoTS): user_guide/SARE_SFIM.md
  - Meta-association rules:
    - ARM.meta_rules: user_guide/ARM/meta_rules.md
  - Visualization:
    - VizARM.AREtoGraph: user_guide/VizARM.md
  - Preprocessing:
    - preprocessing.FuzzyLib: user_guide/preprocessing/FuzzyLib.md
- About:
  - How To Contribute: CONTRIBUTING.md
  - Contributors: contributors.md
  - License: license.md
  - Citing ARMxtend: cite.md
